apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: muffin-wallet-replicaset
  namespace: aksum
  labels:
    app: muffin-wallet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: muffin-wallet
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: muffin-wallet
    spec:
      containers:
        - name: muffin-wallet
          image: aksumshevkevich/muffin-wallet:lates
          imagePullPolice: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
              name: muffin-wallet-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

