---

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/muffin_wallet
    username: muffin-wallet
    password: muffin-wallet


currency:
  service:
    url: http://localhost:8080/rate

logging.file.name: logs/app.log
